version: '3'
services:
  applitrak-app:
    build: .
    ports:
      - "${PORT}:3001"
    environment:
      - NODE_ENV=dev
    hostname: applitrakHost
    volumes:
      - app:/app
    networks:
      - network
    depends_on:
      - applitrak-db

  applitrak-db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "${DB_PORT}:3306"
    hostname: "${DB_HOSTNAME}"
    volumes:
      - sql:/var/lib/mysql
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  app:
  sql: