version: '3'
services:
  web:
    build: .
    ports:
      - "${WEB_PORT}:3001"
    environment:
      - NODE_ENV=dev
    hostname: applitrak-app
    volumes:
      - app:/app
    networks:
      - network
    depends_on:
      - db

  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "${DB_PORT}:3306"
    hostname: applitrak-db
    volumes:
      - sql:/var/lib/mysql
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  app:
  sql: